# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  ResourceGroupName:                "Automation"
  AutomationAccountName:            "ScriptsAutoAcc"
  Location:                         "WestEurope"
  RunbookName:                      "ViaPipelineScript"
  RunbookType:                      "PowerShell"
  RunbookPath:                      $(System.DefaultWorkingDirectory)\Script.ps1
  WebhookName:                      "PipelineScriptWebhook"
  ResourceProvisioningScriptPath:   $(System.DefaultWorkingDirectory)\ResourceProvisioning.ps1



steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World!!!"'
    errorActionPreference: 'stop'
  displayName: 'Write to the Host: Hello World!'

- task: AzurePowerShell@4
  inputs:
    azureSubscription: SvcConn-AlMargoi
    scriptType: filePath
    scriptPath: $(ResourceProvisioningScriptPath)
    scriptArguments:
      -ResourceGroupName         $(ResourceGroupName)   
      -AutomationAccountName     $(AutomationAccountName) 
      -Location                  $(Location) 
      -RunbookName               $(RunbookName) 
      -RunbookType               $(RunbookType) 
      -RunbookPath               $(RunbookPath) 
      -WebhookName               $(WebhookName)
    azurePowerShellVersion: latestVersion
  displayName: "Create RG, AutAccount, Runbook, Import runbook, publish, create Webhook"
  





 
