# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World!"'
    errorActionPreference: 'stop'
  displayName: 'Write to the Host: Hello World!'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Import-Module AzureRm.Automation'
    errorActionPreference: 'stop'
  displayName: 'Import the AzureRM.Automation module.'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-AzureRMAutomationAccount | FL'
    errorActionPreference: 'stop'
  displayName: 'Attempt to fetch Automation Accounts'