# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  ResourceGroup: "AutomationRG"
  AutomationAccountName: "AutoAutoAcc"
  Location: "WestEurope"
  RunbookName: "PipelineScript"
  RunbookType: "PowerShell"
  SourceScriptPath: $(System.DefaultWorkingDirectory)\Script.ps1



steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World!!!"'
    errorActionPreference: 'stop'
  displayName: 'Write to the Host: Hello World!'

- task: AzurePowerShell@4
  inputs:
    azureSubscription: SvcConn-AlMargoi
    scriptType: inlineScript
    Inline: New-AzAutomationAccount -Name $(AutomationAccountName) -ResourceGroup $(ResourceGroup) -Location $(Location) -Plan "Free"
    azurePowerShellVersion: latestVersion
  displayName: "Create 'AutoAutoAcc' automation account."
  
- task: AzurePowerShell@4
  inputs:
    azureSubscription: SvcConn-AlMargoi
    scriptType: inlineScript
    Inline: |
      Import-AzAutomationRunbook -Name $(RunbookName) -Path $(SourceScriptPath) `
        -ResourceGroupName $(ResourceGroup) -AutomationAccountName $(AutomationAccountName) -Type $(RunbookType)
    azurePowerShellVersion: latestVersion
  displayName: "Import the script to the Automation Account."

- task: AzurePowerShell@4
  inputs:
    azureSubscription: SvcConn-AlMargoi
    scriptType: inlineScript
    Inline: |
      try
      {
        Publish-AzAutomationRunbook -AutomationAccountName $(AutomationAccountName) `
          -Name $(RunbookName) -ResourceGroupName $(ResourceGroup) -ErrorAction STOP
      }
      catch
      {
        $Exception = $_.Exception
        if($Exception.Message -notlike "*already exists*")
        {
          Write-Output "$($Exception.GetType()) - $($Exception.Message)"
          throw $Exception
        }
        else
        {
          Write-Output "The runbook already exists. Expected. Continuing"
        }
      }
    azurePowerShellVersion: latestVersion
  displayName: "Publish the previous script"



 
